language: python
python:
  - 3.5
install: 
  - pip install .
script:
  - coverage run pscheduler service start
  - coverage run pscheduler hosts
  - coverage run pscheduler jobs
  - coverage run pscheduler sub "sleep 1"
